manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: homerowkb
      url-base: https://github.com/homerowkb
  projects:
    - name: zmk
      remote: homerowkb
      revision: enrico/add-multiprofile-support
      import:
        - app/west.yml
        - app/CMakeLists.txt
        - app/include/dt-bindings/zmk/profile.h
        - app/include/zmk/keymap.h
        - app/src/behaviors/behavior_profile.c
        - app/src/keymap.c
        - app/src/studio/keymap_subsystem.c
    - name: zmk-keyboard-radiata
      remote: homerowkb
      revision: main
  self:
    path: config
